[build-system]
requires = [ "setuptools>=40.8.0", "wheel", "versioneer-518" ]
build-backend = "setuptools.build_meta"

[tool.pyright]
include = [ "yancc/*.py", "tests/*.py" ]
exclude = [
  "yancc/_version.py",
  "versioneer.py",
  "docs/conf.py",
  "local/*",
  "*/.ipynb_checkpoints/*"
]
