---
name: Dependency test JAX
on:
  pull_request:
    types:
      - labeled
  workflow_dispatch: null
jobs:
  jax_tests:
    if: ${{ github.event.label.name == 'test_jax' && github.event_name ==
      'pull_request' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jax-version:
          - 0.4.30
          - 0.4.31
          - 0.4.33
          - 0.4.34
          - 0.4.35
          - 0.4.36
          - 0.4.37
          - 0.4.38
          - 0.5.0
          - 0.5.1
          - 0.5.2
          - 0.5.3
          - 0.6.0
          - 0.6.1
          - 0.6.2
          - 0.7.0
          - 0.7.1
          - 0.7.2
          - 0.8.0
          - 0.8.1
          - 0.8.2
          - 0.9.0
          - 0.8.3
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies with given JAX version
        run: |
          sed -i '/jax/d' ./requirements.txt
          sed -i '1i\jax == ${{ matrix.jax-version }}' ./requirements.txt
          cat ./requirements.txt
          pip install -r ./requirements-dev.txt
      - name: Verify dependencies
        run: |
          python --version
          pip --version
          pip list
      - name: Test with pytest
        run: |
          pwd
          lscpu
          python -m pytest tests/test_solve.py \
            --durations=0 \
            --maxfail=1 \
