name: Weekly tests

on:
  schedule:
      - cron: '17 9 * * 1'
  workflow_dispatch:

jobs:
  unit_tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        combos: [{group: 1, python_version: '3.10'},
                 {group: 2, python_version: '3.10'},
                 {group: 3, python_version: '3.10'},
                 {group: 4, python_version: '3.10'},
                 {group: 1, python_version: '3.11'},
                 {group: 2, python_version: '3.11'},
                 {group: 3, python_version: '3.11'},
                 {group: 4, python_version: '3.11'},
                 {group: 1, python_version: '3.12'},
                 {group: 2, python_version: '3.12'},
                 {group: 3, python_version: '3.12'},
                 {group: 4, python_version: '3.12'},
                 {group: 1, python_version: '3.13'},
                 {group: 2, python_version: '3.13'},
                 {group: 3, python_version: '3.13'},
                 {group: 4, python_version: '3.13'}]

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.combos.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.combos.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements-dev.txt
          pip list
      - name: Test with pytest
        run: |
          pwd
          lscpu
          python -m pytest -v  \
            --durations=0 \
            --cov-report xml:cov.xml \
            --cov-config=setup.cfg \
            --cov=yancc/ \
            --splits 4 \
            --group ${{ matrix.combos.group }} \
            --splitting-algorithm least_duration \
            --db ./prof.db
      - name: save coverage file and plot comparison results
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: unit_test_artifact-${{ matrix.combos.python_version }}-${{ matrix.combos.group }}
          path: |
            ./cov.xml
            ./prof.db
      - name: Upload coverage
        id : codecov
        uses: codecov/codecov-action@v5
        with:
          name: codecov-umbrella
          files: ./cov.xml
          fail_ci_if_error: true
          verbose: true
